FROM python:3.10.5-slim AS builder

# 设置环境变量
ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONUNBUFFERED 1

# 工作目录
WORKDIR /usr/backend

# 安装构建依赖
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    libgl1-mesa-glx \
    libglib2.0-0

# 复制 requirements.txt 并安装依赖
RUN pip install --no-cache-dir opencv-python numpy redis redis-om python-dotenv

# 复制应用代码
COPY . /usr/backend/

CMD ["python3", "run_mock_camera.py"]